version: 2.1
orbs:
    node: circleci/node@5.0.2
    browser-tools: circleci/browser-tools@1.4.0
jobs:
    build-and-test:
        parameters:
            node-version:
                type: string
        executor:
            name: node/default
            # TODO: switch back to 'lts'. Temp workaround for issues with lts v16.
            # https://github.com/salesforce/sa11y/issues/82
            tag: << parameters.node-version >>
        steps:
            - browser-tools/install-chrome
            - browser-tools/install-chromedriver
            - checkout
            - run: yarn build:ci
            - run: yarn test:ci
            - run: yarn codecov
workflows:
    matrix-tests:
        jobs:
            - build-and-test:
                  matrix:
                      parameters:
                          node-version:
                              - '14.18.1'
